"""Broker adapter boundary contracts.

No real broker implementation lives here yet.
"""

from .adapter import BrokerAdapter
from .alpaca import AlpacaBrokerAdapter, AlpacaBrokerCapabilities, AlpacaBrokerError, AlpacaBrokerErrorDetails
from .capabilities import (
    BrokerAssetClass,
    BrokerCapabilityMatrix,
    BrokerCapabilityViolation,
    BrokerErrorFamily,
    BrokerErrorSeverity,
    BrokerOperation,
    BrokerOperatorAdvisory,
    BrokerOrderClass,
    BrokerOrderPreflightRequest,
    BrokerOrderPreflightResult,
    BrokerViolationCode,
    MarketRulePreflightRequest,
    MarketRulePreflightResult,
    MarketRuleViolation,
    MarketRuleViolationCode,
    MarketSessionState,
)
from .fake import FakeBrokerAdapter
from .models import (
    AccountTradeSyncState,
    AccountTradeSyncStatus,
    BrokerAccountSnapshot,
    BrokerAdapterError,
    BrokerErrorEvent,
    BrokerFillUpdateEvent,
    BrokerOpenOrderSnapshot,
    BrokerOrderMapping,
    BrokerOrderResult,
    BrokerOrderStatus,
    BrokerOrderUpdateEvent,
    BrokerPositionDelta,
    BrokerPositionSide,
    BrokerPositionSnapshot,
    BrokerReconciliationIssue,
    BrokerReconciliationIssueType,
    BrokerReconciliationReport,
    BrokerSyncState,
)
from .preflight import (
    AlpacaBrokerPreflightService,
    MarketRulePreflightService,
    build_broker_order_preflight_request,
    build_market_rule_preflight_request,
)
from .stream import AlpacaAccountStreamAdapter, BrokerStreamEvent, BrokerStreamRouter, BrokerStreamRunner
from .sync import BrokerSync, BrokerSyncService

__all__ = [
    "AlpacaBrokerPreflightService",
    "AlpacaBrokerAdapter",
    "AlpacaBrokerCapabilities",
    "AlpacaBrokerError",
    "AlpacaBrokerErrorDetails",
    "AccountTradeSyncState",
    "AccountTradeSyncStatus",
    "BrokerAccountSnapshot",
    "BrokerAdapter",
    "BrokerAdapterError",
    "BrokerErrorEvent",
    "BrokerAssetClass",
    "BrokerCapabilityMatrix",
    "BrokerCapabilityViolation",
    "BrokerErrorFamily",
    "BrokerErrorSeverity",
    "AlpacaAccountStreamAdapter",
    "BrokerFillUpdateEvent",
    "BrokerOpenOrderSnapshot",
    "BrokerOrderMapping",
    "BrokerOperation",
    "BrokerOperatorAdvisory",
    "BrokerOrderClass",
    "BrokerOrderPreflightRequest",
    "BrokerOrderPreflightResult",
    "BrokerOrderResult",
    "BrokerOrderStatus",
    "BrokerOrderUpdateEvent",
    "BrokerPositionDelta",
    "BrokerPositionSide",
    "BrokerPositionSnapshot",
    "BrokerReconciliationIssue",
    "BrokerReconciliationIssueType",
    "BrokerReconciliationReport",
    "BrokerSync",
    "BrokerSyncService",
    "BrokerSyncState",
    "BrokerStreamEvent",
    "BrokerStreamRouter",
    "BrokerStreamRunner",
    "BrokerViolationCode",
    "FakeBrokerAdapter",
    "MarketRulePreflightRequest",
    "MarketRulePreflightResult",
    "MarketRuleViolation",
    "MarketRuleViolationCode",
    "MarketRulePreflightService",
    "MarketSessionState",
    "build_broker_order_preflight_request",
    "build_market_rule_preflight_request",
]
