"""Canonical Trading OS domain schemas.

These are Pydantic contracts only. They are not database models and they do not
own API, broker, or persistence behavior.
"""

from .chart_lab import ChartLabSession
from .execution_style import ExecutionStyleVersion, OrderType, TimeInForce
from .program import ProgramStatus, ProgramVersion, ValidationStatus
from .research_evidence import (
    BacktestRun,
    ChartLabPreviewEvidence,
    OptimizationRun,
    PromotionEvidenceBundle,
    SimulationRunEvidence,
    WalkForwardRun,
)
from .research_job import (
    ResearchJob,
    ResearchJobKind,
    ResearchJobProgress,
    ResearchJobStatus,
    is_terminal as research_job_is_terminal,
    job_summary as research_job_summary,
)
from .risk_decision_card import (
    RiskCalculationStep,
    RiskDecisionCard,
    RiskDecisionMode,
    RiskDecisionStatus,
)
from .risk_plan import (
    RiskPlan,
    RiskPlanConfig,
    RiskPlanSizingMethod,
    RiskPlanSource,
    RiskPlanStatus,
    RiskPlanTier,
    RiskPlanVersion,
    RiskPlanVersionStatus,
    WholeShareRounding,
)
from .risk_profile import RiskProfileVersion
from .simulation import GovernorMode, SimulationSession
from .signal_plan import (
    AccountEvaluationStatus,
    AccountParticipationDecision,
    AccountSignalPlanEvaluation,
    GovernorDecisionStatus,
    GovernorDecisionTrace,
    PositionExplanationContext,
    RiskResolvedLegAllocation,
    RiskResolverResult,
    SignalPlan,
    SignalPlanEntry,
    SignalPlanIntent,
    SignalPlanLogicalExit,
    SignalPlanLogicalExitScope,
    SignalPlanRunner,
    SignalPlanRunnerManagement,
    SignalPlanSide,
    SignalPlanStatus,
    SignalPlanStop,
    SignalPlanTarget,
    SignalPlanTargetAction,
)
from .strategy import (
    CandidateSide,
    CandidateTradeIntent,
    ConditionGroup,
    ConditionNode,
    ConditionOperator,
    IntentType,
    LogicalExitRule,
    LogicalExitRuleKind,
    SignalRule,
    StrategyVersion,
)
from .strategy_draft import (
    StrategyDraft,
    StrategyDraftBacktestPlan,
    StrategyDraftComponentKind,
    StrategyDraftComponentMatch,
    StrategyDraftStep,
    StrategyDraftStepStatus,
    StrategyDraftValidation,
)
from .strategy_controls import (
    AllowedDirections,
    SessionName,
    SessionPreference,
    SessionWindow,
    StrategyControlsVersion,
    TradingHorizon,
)
from .trading_mode import (
    BROKER_MODES,
    CHART_LAB_MODES,
    SIM_LAB_MODES,
    TradingMode,
    TradingModeBoundaryError,
    validate_trading_mode_boundary,
)
from .universe import UniverseSnapshot, UniverseSymbol
from .validation import EvidenceKind, ValidationEvidence

__all__ = [
    "CandidateSide",
    "CandidateTradeIntent",
    "AccountEvaluationStatus",
    "AccountParticipationDecision",
    "AccountSignalPlanEvaluation",
    "BacktestRun",
    "ChartLabSession",
    "ChartLabPreviewEvidence",
    "ConditionGroup",
    "ConditionNode",
    "ConditionOperator",
    "EvidenceKind",
    "ExecutionStyleVersion",
    "GovernorDecisionStatus",
    "GovernorDecisionTrace",
    "GovernorMode",
    "IntentType",
    "LogicalExitRule",
    "LogicalExitRuleKind",
    "OrderType",
    "OptimizationRun",
    "ProgramStatus",
    "ProgramVersion",
    "PromotionEvidenceBundle",
    "ResearchJob",
    "ResearchJobKind",
    "ResearchJobProgress",
    "ResearchJobStatus",
    "research_job_is_terminal",
    "research_job_summary",
    "RiskCalculationStep",
    "RiskDecisionCard",
    "RiskDecisionMode",
    "RiskDecisionStatus",
    "RiskPlan",
    "RiskPlanConfig",
    "RiskPlanSizingMethod",
    "RiskPlanSource",
    "RiskPlanStatus",
    "RiskPlanTier",
    "RiskPlanVersion",
    "RiskPlanVersionStatus",
    "WholeShareRounding",
    "RiskProfileVersion",
    "RiskResolvedLegAllocation",
    "RiskResolverResult",
    "SignalRule",
    "SignalPlan",
    "SignalPlanEntry",
    "SignalPlanIntent",
    "SignalPlanLogicalExit",
    "SignalPlanLogicalExitScope",
    "SignalPlanRunner",
    "SignalPlanRunnerManagement",
    "SignalPlanSide",
    "SignalPlanStatus",
    "SignalPlanStop",
    "SignalPlanTarget",
    "SignalPlanTargetAction",
    "SimulationRunEvidence",
    "SimulationSession",
    "BROKER_MODES",
    "CHART_LAB_MODES",
    "SIM_LAB_MODES",
    "AllowedDirections",
    "SessionName",
    "SessionPreference",
    "SessionWindow",
    "StrategyControlsVersion",
    "TradingHorizon",
    "StrategyDraft",
    "StrategyDraftBacktestPlan",
    "StrategyDraftComponentKind",
    "StrategyDraftComponentMatch",
    "StrategyDraftStep",
    "StrategyDraftStepStatus",
    "StrategyDraftValidation",
    "StrategyVersion",
    "TimeInForce",
    "TradingMode",
    "TradingModeBoundaryError",
    "UniverseSnapshot",
    "UniverseSymbol",
    "ValidationEvidence",
    "ValidationStatus",
    "WalkForwardRun",
    "validate_trading_mode_boundary",
]
